spring.application.name=Amajon

spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:mem:2139fc2c-b383-40c4-a677-f50d51c64c4b

spring.jpa.show-sql =true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

project.image = images/